services:
  database:
    image: postgres:16
    container_name: ffi-inventory-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Riyadh
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - /schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # - /seed.sql:/docker-entrypoint-initdb.d/seed.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - "5432:5432" 
  
  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000" # HTTP Port
      - "5678:5678" # Debug Port
    environment:
      - PYTHONUNBUFFERED=1
    command: /scripts/start-dv.sh
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/src          # mount entire project
      - node_modules:/src/node_modules   # prevent node_modules overwrite

    ports:
      - "3000:3000"
      - "9229:9229" # Debug Port
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PRIVATE_WATCHPACK_POLLING=true
      - NODE_OPTIONS=--enable-source-maps

    command: >
      node --inspect=0.0.0.0:9229
      ./node_modules/next/dist/bin/next dev



volumes:
  pgdata:
  node_modules: